[package]
name = "android-bridge"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
noda_core = { package = "core", path = "../core" }
shared = { path = "../shared" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
jni = { version = "0.21" }
ulid = "1.2.1"
gray_matter = "0.2"
chrono = "0.4"
mime_guess = "2.0"
base64 = "0.22"
